// DataTable/Angular/src/components/data-table/data-table.component.ts
import { Component, OnInit } from '@angular/core';
import users from './users.json';
import { CommonModule } from '@angular/common';
import { BehaviorSubject, combineLatest } from 'rxjs';

@Component({
  selector: 'app-data-table',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './data-table.component.html',
  styleUrls: ['./data-table.component.css'],
})
export class DataTableComponent implements OnInit {
  options = [5, 10, 20];
  columns = [
    { label: 'ID', key: 'id' },
    { label: 'Name', key: 'name' },
    { label: 'Age', key: 'age' },
    { label: 'Occupation', key: 'occupation' },
  ];

  _pageSubject = new BehaviorSubject<number>(1);
  _pageSizeSubject = new BehaviorSubject<number>(5);
  data: any[] = [];
  text = '';
  _totalPages = 0;

  ngOnInit() {
    combineLatest([this._pageSubject, this._pageSizeSubject]).subscribe(
      ([page, pageSize]) => {
        this.draw(page, pageSize);
      }
    );
  }

  draw(page: number, pageSize: number) {
    const { pageUsers, totalPages } = this.paginateUsers(users, page, pageSize);
    this.data = pageUsers;
    this._totalPages = totalPages;
    this.text = `Page ${page} of ${this._totalPages}`;
  }

  paginateUsers(usersList: any[], page: number, pageSize: number) {
    const start = (page - 1) * pageSize;
    const pageUsers = usersList.slice(start, start + pageSize);
    const totalPages = Math.ceil(usersList.length / pageSize);
    return { pageUsers, totalPages };
  }

  handleChange(e: Event) {
    const newPageSize = parseInt((e.target as HTMLSelectElement).value, 10);
    this._pageSubject.next(1); // Reset to first page on page size change
    this._pageSizeSubject.next(newPageSize);
  }

  clickNext() {
    if (this._pageSubject.value < this._totalPages) {
      this._pageSubject.next(this._pageSubject.value + 1);
    }
  }

  clickPrev() {
    if (this._pageSubject.value > 1) {
      this._pageSubject.next(this._pageSubject.value - 1);
    }
  }
}

<div>
    <table>
        <thead>
            <tr>
                <th *ngFor="let col of columns" id="{{col.key}}">{{col.label}}</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let user of data">
                <td>{{ user.id }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.age }}</td>
                <td>{{ user.occupation }}</td>
            </tr>
        </tbody>
    </table>
    <hr />
    <div class="pagination">
        <select aria-label="Page size" (change)="handleChange($event)">
            <option *ngFor="let option of options" value="{{option}}">Show {{option}}</option>
        </select>
        <div class="pages">
            <button [disabled]="_pageSubject.value === 1" (click)="clickPrev()">
                Prev
            </button>
            <span aria-label="Page number">
                {{text}}
            </span>
            <button [disabled]="_pageSubject.value === _totalPages" (click)="clickNext()">
                Next
            </button>
        </div>
    </div>
</div>

// DataTable/Vue/src/components/DataTable.vue
<script setup>
import { onMounted, ref, watch } from "vue";
import users from "./users.json";

// Cấu hình các cột
const columns = [
  { label: "ID", key: "id" },
  { label: "Name", key: "name" },
  { label: "Age", key: "age" },
  { label: "Occupation", key: "occupation" },
];

// Thiết lập trạng thái cho phân trang
const page = ref(1);
const pageSize = ref(5);
const pageUsers = ref([]);
const totalPages = ref(0);

// Hàm phân trang
function paginateUsers(usersList, page, pageSize) {
  const start = (page - 1) * pageSize;
  const end = start + pageSize;

  return {
    pageUsers: usersList.slice(start, end),
    totalPages: Math.ceil(usersList.length / pageSize),
  };
}

// Thay đổi kích thước trang
function handleChange(event) {
  pageSize.value = parseInt(event.target.value);
}

// Cập nhật phân trang
function updatePagination() {
  const { pageUsers: paginatedUsers, totalPages: total } = paginateUsers(
    users,
    page.value,
    pageSize.value
  );
  pageUsers.value = paginatedUsers;
  totalPages.value = total;
}

// Watchers để theo dõi thay đổi của page và pageSize
watch(pageSize, () => {
  page.value = 1; // Cập nhật page về 1 khi pageSize thay đổi
  updatePagination();
});

watch(page, () => {
  updatePagination();
});

// Khởi tạo phân trang khi component được mount
onMounted(() => {
  updatePagination();
});
</script>

<template>
  <div>
    <table>
      <thead>
        <tr>
          <th v-for="col in columns" :key="col.key">{{ col.label }}</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="user in pageUsers" :key="user.id">
          <td>{{ user.id }}</td>
          <td>{{ user.name }}</td>
          <td>{{ user.age }}</td>
          <td>{{ user.occupation }}</td>
        </tr>
      </tbody>
    </table>
    <hr />
    <div class="pagination">
      <select aria-label="Page size" @change="handleChange">
        <option v-for="value in [5, 10, 20]" :key="value" :value="value">
          Show {{ value }}
        </option>
      </select>
      <div class="pages">
        <button :disabled="page === 1" @click="page--">Prev</button>
        <span aria-label="Page number">
          Page {{ page }} of {{ totalPages }}
        </span>
        <button :disabled="page === totalPages" @click="page++">Next</button>
      </div>
    </div>
  </div>
</template>

<style scoped></style>
