// Tabs/Angular/src/components/tabs/tabs.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-tabs',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './tabs.component.html',
  styleUrl: './tabs.component.css',
})
export class TabsComponent {
  @Input()
  items!: any[];

  @Input()
  defaultValue!: string;

  value = '';

  ngOnInit(): void {
    this.value = this.defaultValue ?? this.items[0].value;
  }

  setValue(newValue: string): void {
    this.value = newValue;
  }
}

<div class="tabs">
    <div class="tabs-list">
        <button *ngFor="let item of items" type="button" [class]="
          [
            'tabs-list-item',
            item.value === value
              ? 'tabs-list-item--active'
              : ''
          ].join(' ')
        " (click)="setValue(item.value)">
            {{ item.label }}
        </button>
    </div>
    <div>
        <div *ngFor="let item of items" [hidden]="item.value !== value">
            {{ item.panel }}
        </div>
    </div>
</div>

// Tabs/React/src/components/Tabs.tsx
import { useState } from "react";

export default function Tabs({ defaultValue, items }: any) {
  const [value, setValue] = useState<any>(defaultValue ?? items[0].value);

  return (
    <div className="tabs">
      <div className="tabs-list">
        {items.map(({ label, value: itemValue }: any) => {
          const isActiveValue = itemValue === value;

          return (
            <button
              key={itemValue}
              type="button"
              className={[
                "tabs-list-item",
                isActiveValue && "tabs-list-item--active",
              ]
                .filter(Boolean)
                .join(" ")}
              onClick={() => {
                setValue(itemValue);
              }}
            >
              {label}
            </button>
          );
        })}
      </div>
      <div>
        {items.map(({ panel, value: itemValue }: any) => (
          <div key={itemValue} hidden={itemValue !== value}>
            {panel}
          </div>
        ))}
      </div>
    </div>
  );
}
