// HolyGrail/Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HeaderComponent } from './components/header/header.component';
import { FooterComponent } from './components/footer/footer.component';
import { SidebarComponent } from './components/sidebar/sidebar.component';
import { NavigationComponent } from './components/navigation/navigation.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    RouterOutlet,
    FormsModule,
    ReactiveFormsModule,
    HeaderComponent,
    FooterComponent,
    SidebarComponent,
    NavigationComponent,
  ],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  title = 'Angular';
}

<app-header></app-header>
<div class="columns">
  <app-navigation></app-navigation>
  <main>Main</main>
  <app-sidebar></app-sidebar>
</div>
<app-footer></app-footer>

// HolyGrail/React/src/App.tsx
import { useState } from "react";
import Header from "./Components/Header";
import Navigation from "./Components/Navigation";
import Sidebar from "./Components/Sidebar";
import Footer from "./Components/Footer";

function App() {
  return (
    <>
      <Header />
      <div className="columns">
        <Navigation />
        <main>Main</main>
        <Sidebar />
      </div>
      <Footer />
    </>
  );
}

export default App;
