// HolyGrail/React/src/App.tsx
import { useState } from "react";
import Header from "./Components/Header";
import Navigation from "./Components/Navigation";
import Sidebar from "./Components/Sidebar";
import Footer from "./Components/Footer";

function App() {
  return (
    <>
      <Header />
      <div className="columns">
        <Navigation />
        <main>Main</main>
        <Sidebar />
      </div>
      <Footer />
    </>
  );
}

export default App;

// HolyGrail/Vue/src/App.vue
<script setup lang="ts">
import Footer from "./components/Footer.vue";
import Header from "./components/Header.vue";
import Navigation from "./components/Navigation.vue";
import Sidebar from "./components/Sidebar.vue";
</script>

<template>
  <Header />
  <div className="columns">
    <Navigation />
    <main>Main</main>
    <Sidebar />
  </div>
  <Footer />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
