// MortgageCalculator/React/src/App.tsx
import { useState } from "react";

export default function App() {
  const [monthlyPayment, setMonthlyPayment] = useState("");
  const [totalPayment, setTotalPayment] = useState("");
  const [totalInterest, setTotalInterest] = useState("");

  function onSubmit(event: any) {
    event.preventDefault(); // Prevent page reload on form submission.

    const data: any = new FormData(event.target);

    // Get and convert input values.
    const loanAmount = parseFloat(data.get("loan-amount"));
    const monthlyInterestRate =
      parseFloat(data.get("interest-rate")) / 100 / 12;
    const loanTermInMonths = parseFloat(data.get("loan-term")) * 12;

    // Calculate monthly mortgage payment.
    const monthlyPaymentAmount =
      (loanAmount * monthlyInterestRate) /
      (1 - 1 / Math.pow(1 + monthlyInterestRate, loanTermInMonths));
    const totalPayment = monthlyPaymentAmount * loanTermInMonths;

    const currencyFormatter = new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: "USD",
    });

    // Display monthly payment amount.
    setMonthlyPayment(currencyFormatter.format(monthlyPaymentAmount));

    // Display total payment amount.
    setTotalPayment(currencyFormatter.format(totalPayment));

    // Display total interest amount.
    setTotalInterest(currencyFormatter.format(totalPayment - loanAmount));
  }

  return (
    <div className="mortgage-calculator">
      <form className="mortgage-calculator-form" onSubmit={onSubmit}>
        <div>
          <label>
            Loan Amount:{" "}
            <input
              type="number"
              name="loan-amount"
              defaultValue="100000"
              min="1"
              required
            />
          </label>
        </div>
        <div>
          <label>
            Loan Term (years):{" "}
            <input
              type="number"
              name="loan-term"
              defaultValue="30"
              min="1"
              required
            />
          </label>
        </div>
        <div>
          <label>
            Interest Rate (%):{" "}
            <input
              type="number"
              name="interest-rate"
              defaultValue="3"
              step="0.01"
              min="0.01"
              required
            />
          </label>
        </div>
        <div>
          <button type="submit">Calculate</button>
        </div>
      </form>
      <hr />
      <div aria-live="polite" className="mortgage-calculator-results">
        <div>
          Monthly Payment Amount: <strong>{monthlyPayment}</strong>
        </div>
        <div>
          Total Payment Amount: <strong>{totalPayment}</strong>
        </div>
        <div>
          Total Interest Paid: <strong>{totalInterest}</strong>
        </div>
      </div>
    </div>
  );
}

// MortgageCalculator/Angular/src/app/app.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import {
  FormBuilder,
  FormGroup,
  FormsModule,
  NgForm,
  ReactiveFormsModule,
} from '@angular/forms';
import { Mortgage } from '../models/mortgage.model';
import { FormComponent } from '../components/form/form.component';
import { CommonModule } from '@angular/common';
import { FormState } from '../models/formState.model';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    RouterOutlet,
    FormsModule,
    ReactiveFormsModule,
    FormComponent,
    CommonModule,
  ],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {
  mortgage!: Mortgage;

  formSubmit(formData: FormGroup<any>): void {
    const mortgageData = formData as unknown as FormState;
    const loanAmount = mortgageData.loanAmount;
    const monthlyInterestRate = mortgageData.interestRate / 100 / 12;
    const loanTermInMonths = mortgageData.loanTerm * 12;
    const monthlyPaymentAmount =
      (loanAmount * monthlyInterestRate) /
      (1 - Math.pow(1 + monthlyInterestRate, -loanTermInMonths));
    const totalPayment = monthlyPaymentAmount * loanTermInMonths;
    const currencyFormatter = new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
    });
    this.mortgage = {
      monthlyPayment: currencyFormatter.format(monthlyPaymentAmount),
      totalPayment: currencyFormatter.format(totalPayment),
      totalInterest: currencyFormatter.format(totalPayment - loanAmount),
    };
    console.log(this.mortgage);
  }
}

<div class="mortgage-calculator">
  <app-form (onFormSubmit)="formSubmit($event)" />
  <div aria-live="polite" class="mortgage-calculator-results" *ngIf="mortgage">
    <div>
      Monthly Payment Amount:<strong>{{ mortgage.monthlyPayment }}</strong>
    </div>
    <div>
      Total Payment Amount:<strong>{{ mortgage.totalPayment }}</strong>
    </div>
    <div>
      Total Interest Paid:<strong>{{ mortgage.totalInterest }}</strong>
    </div>
  </div>
</div>
